"use strict";
exports.__esModule = true;
var Product_1 = require("./Product");
var ProductService_1 = require("./ProductService");
var _productService = new ProductService_1.ProductService();
var result;
result = _productService.getProducts();
result = _productService.getById(2);
var p = new Product_1.Product(2, "Sony", "Telefon", 3020);
_productService.saveProduct(p);
_productService.deleteProduct(_productService.getById(3));
result = _productService.getProducts();
console.log(result);
